### ISSUE TITLE
2nd LED behaving strange

### ISSUE THREAD

**Issue by kevkov202** [erotronik/airotic#1]
Hey,

first of all: Great Project! I love the idea and immediately had to build it when I saw it the first time. 

Putting it togeter etc. went really wellt. But I can't get the LEDs to work properly. The 1st one in the chain works as described. But the 2nd one is green when powering up and turns yellow afterwards. When I blow at the sensor the 1st one goes pink as it should but the 2nd one goes green again. 

I have resoldered it 2 times now and even switched both neopixels (with each other and also new ones) to make sure there are no hardware issues. Its always the 2nd one in the chain thats not working. Also measured if the connections are right and that Din/Dout are not touching or the solder pads are bridged.

I am totally out of ideas now, do you maybe have another hint what could be wrong?

**Comment by latexjess** [comment]
I built this project a few weeks ago without any issues - I didn't deviate from the BOM, followed all guides, and used the latest version of each recommended library.

Did you source your LEDs from Adafruit?
Did you test all connections? (perhaps LED grounding)

Can you confirm your library versions?

Here's what I'm using:
- FastLED 3.5.0
- Adafruit BMP280 Library 2.6.2
- Adafruit SPIFlash 3.9.0

Hope this helps!

**Comment by jlatex** [comment]
Oh how strange, if you swap pixels and get the same effect then that points to a possible code issue, but the code is really simple for driving the LEDs. We're using FastLED 3.4.0 library. Are you using the suggested ItsyBitsy and the level shifted pin (5)?  Have you connnected the power for the NeoPixels to 5v and not 3.3v?

**Comment by jlatex** [comment]
If your voltage is correct there is another thing you could do.... since both LEDs are always driven to the exact same colour every time it doesn't really matter that you can address both individually. So you could just connect the DIN of the 2nd LED to the DIN of the 1st LED (instead of the DOUT). Bit of a hack, but it'd probably solve the issue!
