### ISSUE TITLE
Question about Tube spigot

### ISSUE THREAD

**Issue by Zyrin36** [erotronik/airotic#3]
Was wondering is the spigot supposed to fit inside the Bottle adapter caps third hole? With what I got printed they only seam to connect on the outside and it dosnt slide into it.

Not sure if its the material or the way it was printed. Think I can still super glue it on top of the hole if it comes to that.

**Comment by ToyDolly** [comment]
Sorry for the late reply. It should slot in, so check the print settings and make sure all the support was removed. Failing that, a bit of sanding should sort it out
