### ISSUE TITLE
request: possibility to adjust sensitivity of BMP280

### ISSUE THREAD

**Issue by moarkaboom** [erotronik/airotic#8]
First off: Awesome project, thank you so much for providing this to us!!

I was noticing that the sensor would not always trigger with every breath, and that I would have to really breath in fast and deep to trigger the BMP. Would it be possible to adjust the sensitivity? Either by debugging (UART) command, or directly in the code?

**Comment by moarkaboom** [comment]
Nevermind, if you mount the BMP facing the correct side (sensor into the hole), the bubbler triggers just fine.

**Comment by jlatex** [comment]
glad you got it sorted!
